<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="BookingModelView\" />
    <Folder Include="CourtModelView\" />
    <Folder Include="BookingDetailModelView\" />
    <Folder Include="CourTypeModelView\" />
    <Folder Include="BranchModelView\" />
    <Folder Include="BankAccountModelView\" />
    <Folder Include="CalendarTypeModelView\" />
    <Folder Include="TimeSlotModelView\" />
    <Folder Include="PaymentModelView\" />
  </ItemGroup>

</Project>
